---
pipeline:
  build:
    image: quay.io/ukhomeofficedigital/java8-mvn:v3.5.2.1
    commands:
      - "mvn clean package"
    secrets:
      - artifactory_username
      - artifactory_password
    when:
      event:
        - push
