---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dp-noninteractive-doc-check
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dp-noninteractive-doc-check
    spec:
      securityContext:
        runAsUser: 5002
        fsGroup: 5002
      containers:
      - name: dp-noninteractive-doc-check
        image: quay.io/ukhomeofficedigital/dp-noninteractive-doc-check:{{.BUILD_NUMBER}}
        ports:
          - containerPort: 8080
        securityContext:
          runAsNonRoot: true
        env:
          - name: JAVA_OPTS
            value: "-Xms256m -Xmx512m"
        volumeMounts:
        - name: keystore
          mountPath: /etc/keystore
        resources:
          requests:
            memory: "512Mi"
          limits:
            memory: "768Mi"
      - name: cfssl
        image: quay.io/ukhomeofficedigital/cfssl-sidekick-jks:latest
        securityContext:
          runAsNonRoot: true
        args:
        - --certs=/certs
        - --domain=dp-noninteractive-doc-check.${KUBE_NAMESPACE}.svc.cluster.local
        - --expiry=8760h
        - --command='create-keystore.sh /certs/tls.pem /certs/tls-key.pem'
        env:
        - name: KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: certs
          mountPath: /certs
        - name: keystore
          mountPath: /etc/keystore
        - name: bundle
          mountPath: /etc/ssl/certs
          readOnly: true
      volumes:
      - name: bundle
        configMap:
          name: bundle
      - name: keystore
        emptyDir: {}
      - name: certs
        emptyDir: {}
